services:
  cluster-master:
    image: firasj/spark-docker-cluster
    container_name: cluster-master
    depends_on:
      - cluster-slave-1
      - cassandra-server
    ports:
      - "8088:8088"
      - "4040:4040"
      - "19888:19888"
      - "9000:9000"
      - "9870:9870"
    environment:
      - SPARK_DRIVER_MEMORY=6g
      - SPARK_EXECUTOR_MEMORY=6g
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: [ "bash", "/app/app.sh" ]
    tty: true
    networks:
      - spark-cluster

  cluster-slave-1:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-1
    environment:
      - SPARK_EXECUTOR_MEMORY=6g
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    networks:
      - spark-cluster

  cassandra-server:
    image: cassandra
    container_name: cassandra-server
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - spark-cluster

networks:
  spark-cluster:
    driver: bridge
